spring: 
  profiles:
    active:
    - dev
---
server:
  port: 1005
  context-path: /
spring:
  profiles: dev
# 数据源配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.1.254:3306/db_springcloud
    username: root
    password: mysql123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  thymeleaf:
    cache: false  
eureka:
  instance:
    hostname: localhost  #eureka客户端主机实例名称
    appname: microservice-student  #客户端服务名
    instance-id: microservice-student-hystrix:1005 #客户端实例名称
    prefer-ip-address: true #显示IP
  client: 
    service-url: 
      #defaultZone: http://localhost:2001/eureka   #把服务注册到eureka注册中心
      defaultZone:  http://eureka2001.volcano.com:2001/eureka/,http://eureka2002.volcano.com:2002/eureka/,http://eureka2003.volcano.com:2003/eureka/,http://eureka2004.volcano.com:2004/eureka/   #把服务注册到eureka注册中心     
info: 
   groupId: $project.groupId$
   artifactId: $project.artifactId$
   version: $project.version$
   负责人: 张三
   联系电话: 110

---
server:
  port: 1005
  context-path: /
spring:
  profiles: test
# 数据源配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.1.254:3306/db_springcloud
    username: root
    password: mysql123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  thymeleaf:
    cache: false 
eureka:
  instance:
    hostname: localhost  #eureka客户端主机实例名称
    appname: microservice-student  #客户端服务名
    instance-id: microservice-student-hystrix:1005 #客户端实例名称
    prefer-ip-address: true #显示IP
  client: 
    service-url: 
      #defaultZone: http://localhost:2001/eureka   #把服务注册到eureka注册中心
      defaultZone:  http://eureka2001.volcano.com:2001/eureka/,http://eureka2002.volcano.com:2002/eureka/,http://eureka2003.volcano.com:2003/eureka/,http://eureka2004.volcano.com:2004/eureka/   #把服务注册到eureka注册中心   
info: 
   groupId: $project.groupId$
   artifactId: $project.artifactId$
   version: $project.version$
   负责人: 张三
   联系电话: 110
